# src/core/iso_countries.py

ISO_COUNTRIES_ES = {
    "ESP": "España",
    "DEU": "Alemania",
    "FRA": "Francia",
    "GBR": "Reino Unido",
    "ITA": "Italia",
    "PRT": "Portugal",
    "AND": "Andorra",
    "ARG": "Argentina",
    "BRA": "Brasil",
    "CHL": "Chile",
    "COL": "Colombia",
    "CUB": "Cuba",
    "MEX": "México",
    "PER": "Perú",
    "URY": "Uruguay",
    "VEN": "Venezuela",
    "USA": "Estados Unidos",
    "CAN": "Canadá",
    "CHN": "China",
    "JPN": "Japón",
    "RUS": "Rusia",
    "AFG": "Afganistán",
    "ALB": "Albania",
    "DZA": "Argelia",
    "AGO": "Angola",
    "ATG": "Antigua y Barbuda",
    "SAU": "Arabia Saudita",
    "ARM": "Armenia",
    "AUS": "Australia",
    "AUT": "Austria",
    "AZE": "Azerbaiyán",
    "BHS": "Bahamas",
    "BGD": "Bangladés",
    "BRB": "Barbados",
    "BHR": "Baréin",
    "BEL": "Bélgica",
    "BLZ": "Belice",
    "BEN": "Benín",
    "BLR": "Bielorrusia",
    "MMR": "Birmania",
    "BOL": "Bolivia",
    "BIH": "Bosnia y Herzegovina",
    "BWA": "Botsuana",
    "BRN": "Brunéi",
    "BGR": "Bulgaria",
    "BFA": "Burkina Faso",
    "BDI": "Burundi",
    "BTN": "Bután",
    "CPV": "Cabo Verde",
    "KHM": "Camboya",
    "CMR": "Camerún",
    "QAT": "Catar",
    "TCD": "Chad",
    "CYP": "Chipre",
    "VAT": "Ciudad del Vaticano",
    "COM": "Comoras",
    "PRK": "Corea del Norte",
    "KOR": "Corea del Sur",
    "CIV": "Costa de Marfil",
    "CRI": "Costa Rica",
    "HRV": "Croacia",
    "DNK": "Dinamarca",
    "DMA": "Dominica",
    "ECU": "Ecuador",
    "EGY": "Egipto",
    "SLV": "El Salvador",
    "ARE": "Emiratos Árabes Unidos",
    "ERI": "Eritrea",
    "SVK": "Eslovaquia",
    "SVN": "Eslovenia",
    "EST": "Estonia",
    "SWZ": "Esuatini",
    "ETH": "Etiopía",
    "PHL": "Filipinas",
    "FIN": "Finlandia",
    "FJI": "Fiyi",
    "GAB": "Gabón",
    "GMB": "Gambia",
    "GEO": "Georgia",
    "GHA": "Ghana",
    "GRD": "Granada",
    "GRC": "Grecia",
    "GTM": "Guatemala",
    "GIN": "Guinea",
    "GNQ": "Guinea Ecuatorial",
    "GNB": "Guinea-Bisáu",
    "GUY": "Guyana",
    "HTI": "Haití",
    "HND": "Honduras",
    "HUN": "Hungría",
    "IND": "India",
    "IDN": "Indonesia",
    "IRQ": "Irak",
    "IRN": "Irán",
    "IRL": "Irlanda",
    "ISL": "Islandia",
    "MHL": "Islas Marshall",
    "SLB": "Islas Salomón",
    "ISR": "Israel",
    "JAM": "Jamaica",
    "JOR": "Jordania",
    "KAZ": "Kazajistán",
    "KEN": "Kenia",
    "KGZ": "Kirguistán",
    "KIR": "Kiribati",
    "KWT": "Kuwait",
    "LAO": "Laos",
    "LSO": "Lesoto",
    "LVA": "Letonia",
    "LBN": "Líbano",
    "LBR": "Liberia",
    "LBY": "Libia",
    "LIE": "Liechtenstein",
    "LTU": "Lituania",
    "LUX": "Luxemburgo",
    "MDG": "Madagascar",
    "MYS": "Malasia",
    "MWI": "Malaui",
    "MDV": "Maldivas",
    "MLI": "Malí",
    "MLT": "Malta",
    "MAR": "Marruecos",
    "MUS": "Mauricio",
    "MRT": "Mauritania",
    "FSM": "Micronesia",
    "MDA": "Moldavia",
    "MCO": "Mónaco",
    "MNG": "Mongolia",
    "MNE": "Montenegro",
    "MOZ": "Mozambique",
    "NAM": "Namibia",
    "NRU": "Nauru",
    "NPL": "Nepal",
    "NIC": "Nicaragua",
    "NER": "Níger",
    "NGA": "Nigeria",
    "NOR": "Noruega",
    "NZL": "Nueva Zelanda",
    "OMN": "Omán",
    "NLD": "Países Bajos",
    "PAK": "Pakistán",
    "PLW": "Palaos",
    "PAN": "Panamá",
    "PNG": "Papúa Nueva Guinea",
    "PRY": "Paraguay",
    "POL": "Polonia",
    "CAF": "República Centroafricana",
    "CZE": "República Checa",
    "MKD": "Macedonia del Norte",
    "COG": "República del Congo",
    "COD": "República Democrática del Congo",
    "DOM": "República Dominicana",
    "RWA": "Ruanda",
    "ROU": "Rumania",
    "WSM": "Samoa",
    "KNA": "San Cristóbal y Nieves",
    "SMR": "San Marino",
    "VCT": "San Vicente y las Granadinas",
    "LCA": "Santa Lucía",
    "STP": "Santo Tomé y Príncipe",
    "SEN": "Senegal",
    "SRB": "Serbia",
    "SYC": "Seychelles",
    "SLE": "Sierra Leona",
    "SGP": "Singapur",
    "SYR": "Siria",
    "SOM": "Somalia",
    "LKA": "Sri Lanka",
    "ZAF": "Sudáfrica",
    "SDN": "Sudán",
    "SSD": "Sudán del Sur",
    "SWE": "Suecia",
    "CHE": "Suiza",
    "SUR": "Surinam",
    "THA": "Tailandia",
    "TZA": "Tanzania",
    "TJK": "Tayikistán",
    "TLS": "Timor Oriental",
    "TGO": "Togo",
    "TON": "Tonga",
    "TTO": "Trinidad y Tobago",
    "TUN": "Túnez",
    "TKM": "Turkmenistán",
    "TUR": "Turquía",
    "TUV": "Tuvalu",
    "UKR": "Ucrania",
    "UGA": "Uganda",
    "UZB": "Uzbekistán",
    "VUT": "Vanuatu",
    "YEM": "Yemen",
    "DJI": "Yibuti",
    "ZMB": "Zambia",
    "ZWE": "Zimbabue"
}

def get_iso_countries():
    # Sort by country name but keep ESP, DEU, FRA, GBR, ITA at the top if possible, or just sort alphabetically
    return ISO_COUNTRIES_ES
